// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"dev.msiviero/example/internal/app"
	"dev.msiviero/example/internal/grpc_server"
)

// Injectors from wire.go:

func InitializeApp() app.App {
	grpcServer := grpc_server.NewGrpcServer()
	appApp := app.NewApp(grpcServer)
	return appApp
}
